### ISSUE TITLE
Show colors instead of Grayscale

### ISSUE THREAD

**Issue by lakinduakash** [lessthanoptimal/BoofAndroidDemo#15]
I need to show colors in the video stabilization view. I tried to change` ImageType.pl(GrayU8.claa)` . But it gives errors. How can I properly show colors instead of black and white?

**Comment by lessthanoptimal** [comment]
which task?

**Comment by YinXiuYu** [comment]
@lessthanoptimal I have the same issue with the "Object Tracking" task, selected TLD tracking method.

**Comment by lessthanoptimal** [comment]
Going to change it to improve visualization. The reason for that is because that approach requires a gray scale image as input.

**Comment by lessthanoptimal** [comment]
fixed. Latest release will be more colorful.
