### ISSUE TITLE
Unexpected Error 

### ISSUE THREAD

**Issue by shyamkumarm** [lessthanoptimal/BoofAndroidDemo#16]
Unexpected attempt to get register for a value without a register in method `float boofcv.alg.feature.detect.template.TemplateNCC$U8.evaluateMask(int, int)`.

Adding  this line -keep class org.ejml.** in  proguard for my requirement

**Comment by lessthanoptimal** [comment]
could you provide the whole stack trace?

**Comment by shyamkumarm** [comment]
It's an issue from our side, sorry for the inconvenience.
