### ISSUE TITLE
Bug or Misunderstanding in DemoCamera2Activity.java

### ISSUE THREAD

**Issue by esteimle** [lessthanoptimal/BoofAndroidDemo#21]
I was working with the calibrate camera feature in the demo app and I kept getting the wrong resolution after selecting what I wanted in preferences. I tracked it back to this section in DemoCamera2Activity.java. 

```
        for( int i = 0; i < resolutions.length; i++  ) {
            Size r = resolutions[i];
            if( r.getWidth() == target.getWidth() && r.getHeight() == r.getHeight() ) {
                return i;
            }
        }
```

This picks the first resolution where the width matches so if I pick 1280x720 it will actually give me 1280x960 which made me wonder for a while because I thought you might be forcing a 4:3 aspect ratio? So anyway I wasn't sure if this was intentional or just a bug that snuck in.  Should it be:

```
      for( int i = 0; i < resolutions.length; i++  ) {
            Size r = resolutions[i];
            //if( r.getWidth() == target.getWidth() && r.getHeight() == r.getHeight() ) {
            if( r.getWidth() == target.getWidth() && r.getHeight() == target.getHeight() ) {
                return i;
            }
        }
```

**Comment by lessthanoptimal** [comment]
Oh that is almost definitely a bug. Thanks!

**Comment by lessthanoptimal** [comment]
https://github.com/lessthanoptimal/BoofAndroidDemo/commit/ca06b507b3574403eabc4b1bd5f0506cde291acb
