### ISSUE TITLE
CannyEdgeActivity: Is there a possibility to color by EdgeSegment and not not by EdgeContour as in demo?

### ISSUE THREAD

**Issue by ChristopheVersieux** [lessthanoptimal/BoofAndroidDemo#3]
Hello,

In the demo application CannyEdgeActivity.java, you can colorize every EdgeContour  by using the rgb array:
https://github.com/lessthanoptimal/BoofAndroidDemo/blob/master/src/org/boofcv/android/CannyEdgeActivity.java#L105-L112

My concern is that It looks complicated (if not impossible) to colorize every EdgeSegment separately.
(As said in the doc: "Draws each contour using a unique color.  Each segment of each edge is drawn using the same colors.")

An alternative idea would be to be able to remove segments (or event points) I don't want to draw as some home-made algorithms decide if a segment is rejected in the picture or not. Instead of changing color, I simply would like to remove them from the drawing, it would be an acceptable workaround.

I would like to know if the current SDK allow such operation, or if it is something that is impossible 'out of the box' ?

Thank a lot.

**Comment by lessthanoptimal** [comment]
Might be easier if you cut and paste the source code for that function then write your own custom version.  Not really designed to be super flexible.
