### ISSUE TITLE
0.21-SNAPSHOT Dependency 

### ISSUE THREAD

**Issue by LG67** [lessthanoptimal/BoofAndroidDemo#4]
Project error (in Android Studio) due to 0.21-SNAPSHOT dependency

**Comment by lessthanoptimal** [comment]
Thanks for reporting this.  I'll update it soon to a more recent stable version.

**Comment by LG67** [comment]
Great.  Have you heard of FIRST Tech Challenge?  Its an international
robotics game for middle and high school students using Android phones for
control and sensor feedback.  I was hoping to use BoofCV for vision target
acquisition.  FTC could inspire thousands of young BoofCV users.  Would you
be interested in helping me integrate BoofCV with the FTC robot code?

**Comment by lessthanoptimal** [comment]
I'll update it this weekend.

For FIRST, I've heard of it and known several mentions.  I can help a little bit, mostly answer technical questions, but I don't have very much free time at all to do more involved programming.  Working for a medical supply delivery drone start up that's about to deploy to our first customer.

**Comment by tfatrifork** [comment]
@LG67 You can get away with using:
`    compile group: 'org.boofcv', name: 'all', version: '0.22'
    compile group: 'org.boofcv', name: 'android', version: '0.22'
` 
for now if you do not need Disparity and Fiducal ..
I'm looking forward to seeing the BoofCV Android example updated to BoofCV 0.24

**Comment by lessthanoptimal** [comment]
Git code is fixed and updated to 0.24.1
