### ISSUE TITLE
Is the android.app.Application class missing?

### ISSUE THREAD

**Issue by juanestebanj** [lessthanoptimal/BoofAndroidDemo#6]
Hello

I'm understanding how to use BoofCV in android.
I forked this project but...  it seems to me that the main app class android.app.Application is missing.

Could you add to source control this file, or could you please tell me what is the main file for the app?

I'm somewhat new to Android so the above answer might be obvious to others. Please excuse me should that be the case.

Thanks!

**Comment by willchamberlain** [comment]
Android apps launch from Activity classes.

**Comment by juanestebanj** [comment]
Cool!  Thanks Will for your answer. That answers my question! :)
