### ISSUE TITLE
What makes buildType "fast" so fast compared to "debug" ?

### ISSUE THREAD

**Issue by akidee** [lessthanoptimal/BoofAndroidDemo#8]
> fast Turns off debugging and runs at full speed

I want to understand how for example TLD tracking can be so much faster by only disabling debugging and without any Proguard ops.

**Comment by lessthanoptimal** [comment]
I have no idea. At some point google changed how debug mode worked and made it slower. See the issue below

https://github.com/lessthanoptimal/BoofAndroidDemo/issues/5
